# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=32, unique=True)),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gpic', models.CharField(max_length=128, null=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('gweight', models.CharField(default='500g', max_length=200)),
                ('gsum', models.IntegerField(default=0)),
                ('gdesc', models.CharField(max_length=200, null=True)),
                ('gclick', models.IntegerField(default=0)),
                ('gcontent', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'GoodsInfo',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('isdelete', models.BooleanField(default=False)),
                ('desc', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'goodstype',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(db_column='gtype', on_delete=django.db.models.deletion.CASCADE, related_name='goodsinfo', to='goods.GoodsType'),
        ),
    ]
