# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-01 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='utimeCreate',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 19, 43, 15, 63410)),
        ),
    ]
