# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190704_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='utimeCreate',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 19, 45, 59, 921339)),
        ),
    ]
