# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190704_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcategory',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='utimeCreate',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 21, 4, 5, 405909)),
        ),
    ]
