# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=200, unique=True)),
                ('odata', models.DateTimeField(auto_now=True)),
                ('oIsPay', models.BooleanField(default=False)),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('oaddress', models.CharField(default='beijing', max_length=200)),
                ('ouser', models.ForeignKey(db_column='ouser', on_delete=django.db.models.deletion.CASCADE, related_name='orderinfo', to='App.UserInfo')),
            ],
            options={
                'db_table': 'OrderInfo',
            },
        ),
    ]
